### ISSUE TITLE
How to use this plugin with a function only?

### ISSUE THREAD

**Issue by Skaronator** [silvermine/serverless-plugin-cloudfront-lambda-edge#18]
Hi, thanks for this plugin! I've some trouble setting it up. I want to use a function only, no S3, no other data sources. I tried to modify the Readme example but it didn't worked well since it required a Origin.

I found a example from Amazon [here](https://github.com/awslabs/serverless-application-model/blob/a09929bcdd7cd6083d5c344ce5a64208a56bc4a6/examples/apps/cloudfront-response-generation/template.yaml) which use `Type: 'AWS::Serverless::Function'` but after trying that out I'll just get a Error back that this is not a valid value: `Resource with logical name "ServerSideRenderer" is not type AWS::CloudFront::Distribution`.

My current setup with Lambda (not Edge) based on API Gateway. The config looks like this:
```
functions:
  NextJS:
    handler: lambda.handler
    warmup: true
    events:
      - http: ANY /
      - http: ANY {proxy+}
```
