### ISSUE TITLE
Use same lambda for many distributions

### ISSUE THREAD

**Issue by jjchiw** [silvermine/serverless-plugin-cloudfront-lambda-edge#2]
Hi, is there a way to use a lambda in two or more distributions something like this

```
myHandler:
    name: 'myHandler-origin-request'
    handler: handler.main
    memorySize: 128
    timeout: 1
    lambdaAtEdge:
        - distribution: 'distribution1'
           eventType: 'origin-request'
        - distribution: 'distribution2'
           eventType: 'origin-request'
```
