### ISSUE TITLE
Confusing note about environment variables in example

### ISSUE THREAD

**Issue by mrcoles** [silvermine/serverless-plugin-cloudfront-lambda-edge#24]
Thank you very much for including an example serverless.yml file and handler.

However, the note in the example file about environment variables is unclear to me. It seems to suggest that setting the environment variables does nothing? Also, what do these two `SLS_*` do?

```yaml
provider:
   name: aws
   runtime: nodejs6.10 # Because this runs on CloudFront (lambda@edge) it must be 6.10 or greater
   region: ${self:custom.region}
   stage: ${self:custom.stage}
   # Note that Lambda@Edge does not actually support environment variables for lambda
   # functions, but the plugin will strip the environment variables from any function
   # that has edge configuration on it
   environment:
      SLS_SVC_NAME: ${self:service}
      SLS_STAGE: ${self:custom.stage}
```

---

P.S. - it seems like the example also needs a permissive bucket policy, e.g.,

```yaml
    WebsiteBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: "WebsiteBucket"
        PolicyDocument:
          Statement:
            -
              Effect: "Allow"
              Principal: "*"
              Action:
                - "s3:GetObject"
              Resource:
                Fn::Join:
                  - ""
                  -
                    - "arn:aws:s3:::"
                    -
                      Ref: "WebsiteBucket"
                    - "/*"
```
