### ISSUE TITLE
Use new CloudFormation support for Lambda@Edge to avoid duplicate CloudFront updates

### ISSUE THREAD

**Issue by alexcasalboni** [silvermine/serverless-plugin-cloudfront-lambda-edge#7]
As mentioned in [this discussion](https://forums.aws.amazon.com/thread.jspa?threadID=262327), CloudFormation support is now available ([LambdaFunctionAssociation property](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-lambdafunctionassociation.html)).

Of course, this plugin is still super useful because it fixes the `AssumeRolePolicy` Principal and the log group names & env variables problems, but since CloudFormation support is available we can now avoid the double CloudFront distribution update and define the trigger in `serverless.yml` as follows:

```yaml
resources:
  Resources:
    ...
    WebsiteDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          DefaultCacheBehavior:
            ...
            LambdaFunctionAssociations:
              - EventType: 'origin-response'
                LambdaFunctionARN: XXX
```

The problem is that `XXX` should contain the Function Version as well, and there doesn't seem to be a way to easily reference it (CC @alexdebrie @pmuens).
