### ISSUE TITLE
I don't think this is needed

### ISSUE THREAD

**Issue by SHESA-AmitBar** [silvermine/serverless-plugin-cloudfront-lambda-edge#78]
I think you can just do the following to do this natively within AWS SAM:

Specify the lambda resource
```
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/
      FunctionName: !Ref RedirectLambdaName
      Handler: RedirectLambda.handler
      Role: !GetAtt RedirectLambdaFunctionRole.Arn
      Runtime: nodejs12.x
      AutoPublishAlias: live
```

Then in the CloudFront resource, for the lambda function arn:
```
              LambdaFunctionARN: !Ref LambdaFunction.Version
```
